### ISSUE TITLE
Timeunit property not taken into account.

### ISSUE THREAD

**Issue by juanmaneo** [cityzendata/sensision#1]
How to reproduce:
curl http://127.0.0.1:9090/metrics

will always give timestamp in microseconds no matter what unit is set to.

Preliminary digging of the problem:

There is a typo in Sensition.SENSISION_TIME_UNIT

Even after fixing this, there seems to have hardcoded microseconds conversion (* 1000).
A class similar in spirit to warp10.continuum.TimeSource would be useful in sensision.

In Sensision.update method timestamp parameter should be in nanoseconds to avoid losing precision,
also need to convert to the unit used when forcing timestamp.

**Comment by hbs** [comment]
TimeSource is a best effort solution for generating nanosecond absolute timestamps. It is still sensitive to drifts and may need periodic recalibrations.

Please open another issue for integrating a nanosecond time source in Sensision.

**Comment by juanmaneo** [comment]
Thanks for the fix.
